---
kind: pipeline
type: docker
name: integration_test

steps:
  - name: integration test
    image: golang:1.13
    volumes:
      - name: go-cache
        path: /go
    environment:
      STORAGE_TEST_SERVICE_FS:
        from_secret: STORAGE_TEST_SERVICE_FS
    commands:
      - cd tests && go test -race -v ./...

volumes:
  - name: go-cache
    host:
      path: /var/lib/cache/drone/storage/go
---
kind: signature
hmac: c1f2f14f1fdfb9a8887f1c3f6cbd25fd4d4f2e42c9379cdcab2d4f1e85ddfa7f

...
