---
kind: pipeline
type: docker
name: integration_test

steps:
  - name: integration test
    image: golang:1.13
    volumes:
      - name: go-cache
        path: /go
    environment:
      STORAGE_TEST_SERVICE_AZBLOB:
        from_secret: STORAGE_TEST_SERVICE_AZBLOB
      STORAGE_TEST_SERVICE_FS:
        from_secret: STORAGE_TEST_SERVICE_FS
      STORAGE_TEST_SERVICE_QINGSTOR:
        from_secret: STORAGE_TEST_SERVICE_QINGSTOR
      STORAGE_TEST_SERVICE_S3:
        from_secret: STORAGE_TEST_SERVICE_S3
    commands:
      - cd tests && go test -race -v ./...

volumes:
  - name: go-cache
    host:
      path: /var/lib/cache/drone/storage/go
---
kind: signature
hmac: 7fe39fcbf0e32aea2bf1e26580ada7a0ad68671abb50744dcc64fc5cee86e1f7

...
