---
kind: pipeline
type: docker
name: integration_test

steps:
  - name: integration test
    image: golang:1.13
    volumes:
      - name: go-cache
        path: /go
    environment:
      STORAGE_TEST_SERVICE_AZBLOB:
        from_secret: STORAGE_TEST_SERVICE_AZBLOB
      STORAGE_TEST_SERVICE_FS:
        from_secret: STORAGE_TEST_SERVICE_FS
      STORAGE_TEST_SERVICE_GCS:
        from_secret: STORAGE_TEST_SERVICE_GCS
      STORAGE_TEST_SERVICE_QINGSTOR:
        from_secret: STORAGE_TEST_SERVICE_QINGSTOR
      STORAGE_TEST_SERVICE_S3:
        from_secret: STORAGE_TEST_SERVICE_S3
      STORAGE_TEST_SERVICE_COS:
        from_secret: STORAGE_TEST_SERVICE_COS
    commands:
      - cd tests && go test -race -v ./...

volumes:
  - name: go-cache
    host:
      path: /var/lib/cache/drone/storage/go
---
kind: signature
hmac: 4ea099f596192f59bb043298f55e1a163148db30cf99441c0c953d5cf1802b1d

...
