kind: pipeline
type: docker
name: integration_test

steps:
  - name: integration test
    image: golang
    environment:
      STORAGE_TEST_SERVICE_FS:
        from_secret: STORAGE_TEST_SERVICE_FS
    commands:
      - cd tests && go test -race -v ./...
