---
kind: pipeline
type: docker
name: integration_test

steps:
  - name: integration test
    image: golang:1.13
    volumes:
      - name: go-cache
        path: /go
    environment:
      STORAGE_TEST_SERVICE_FS:
        from_secret: STORAGE_TEST_SERVICE_FS
      STORAGE_TEST_SERVICE_QINGSTOR:
        from_secret: STORAGE_TEST_SERVICE_QINGSTOR
      STORAGE_TEST_SERVICE_AZBLOB:
        from_secret: STORAGE_TEST_SERVICE_AZBLOB
    commands:
      - cd tests && go test -race -v ./...

volumes:
  - name: go-cache
    host:
      path: /var/lib/cache/drone/storage/go
---
kind: signature
hmac: e36940a1b7e90d4eb66473ac88a1bc4c47537f7faf7ca9407c0cdfb21f91299e

...
