language: go
os:
  - linux
  - windows
  - osx
go:
  - "1.13"
  - "1.14"

cache:
  directories:
    - /home/travis/gopath

install:
  # code lint tools
  - go get -u golang.org/x/lint/golint
  # Install make for windows
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install make; fi

script:
  - make check
  - make test

after_success:
  - if [ $TRAVIS_OS_NAME = linux ] && [ $TRAVIS_GO_VERSION = "1.14" ]; then bash <(curl -s https://codecov.io/bash); fi
