language: go
go:
  - "1.13"

install:
  # code lint tools
  - go get -u golang.org/x/lint/golint
  # mock generator
  - go get github.com/golang/mock/mockgen
  # go-bindata
  - go get -u github.com/kevinburke/go-bindata/...

script:
  - make check
  - make build
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
