commit_message: '[ci skip] i18n: Translate %original_file_name% to %language%'
append_commit_message: false
files:
  - source: /docs/**/*.md
    ignore:
      - /docs/%locale%/
    translation: /docs/%locale%/**/%original_file_name%
